title = "Static Site Example"
baseURL = "https://www.example.com"
languageCode = "en-us"
theme = "ananke"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en-us"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
	# General information
	author = "someone"
	description = "something"
	copyright = "(c) someone 2019"

    # Images
	logo = "images/logo.png"
	favicon = "images/favicon.png"
  
    # Social
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = "https://github.com/someone"
    gitlab = ""
    linkedin = ""
    mastodon = ""
  
    # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    featured_image = "/images/header.jpg"
    recent_posts_number = 6
